version: '2.2'
services:
  memcached:
    image: 'memcached:latest'
  nginx:
    image: 'nginx:latest'
    expose:
      - '80'
      - '443'
    volumes:
      - './wordpress:/var/www/html:cached'
      - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached'
    depends_on:
      - phpfpm
    networks:
      - default
      - wplocaldocker
    environment:
      CERT_NAME: localhost
      HTTPS_METHOD: noredirect
      VIRTUAL_HOST: 'a8c.test,*.a8c.test'
  phpfpm:
    image: '10up/wp-php-fpm-dev:7.3'
    environment:
      ENABLE_XDEBUG: 'false'
    volumes:
      - './wordpress:/var/www/html:cached'
      - './config/php-fpm/docker-php-ext-xdebug.ini:/etc/php.d/docker-php-ext-xdebug.ini:cached'
      - 'wplocaldockerCache:/var/www/.wp-cli/cache:cached'
      - '~/.ssh:/home/www-data/.ssh:cached'
      - './config/php-fpm/wp-cli.local.yml:/var/www/.wp-cli/config.yml:cached'
    depends_on:
      - memcached
    networks:
      - default
      - wplocaldocker
    dns:
      - 10.0.0.2
networks:
  wplocaldocker:
    external:
      name: wplocaldocker
volumes:
  wplocaldockerCache:
    external:
      name: wplocaldockerCache
